#!/bin/bash

highest_seqno=-1
username="ubuntu"

for host in `cat < "$1" | sort -rn`
do
	seqno=`ssh $username@$host sudo grep seqno /var/lib/mysql/grastate.dat | awk -F' ' '{print $2}'`

	if [[ $seqno -eq -1 ]]
	then
		ssh $username@$host sudo mysqladmin ping &> /dev/null
		if [ $? -eq 0 ]
		then
			bootstrap_host=$host
			break
		fi
	elif [[ $seqno -gt $highest_seqno ]]
	then
		highest_seqno=$seqno
		bootstrap_host=$host
	fi
done

if [[ `ifconfig | grep -c $bootstrap_host` -gt 0 ]]
then
	sudo sed -ie "/safe_to/c\safe_to_bootstrap:\ 1" /var/lib/mysql/grastate.dat
	sudo galera_new_cluster
else

	while [[ `ssh $username@$host sudo mysqladmin ping &> /dev/null` ]]
	do
		if [ $? -eq 0 ]
		then
			break
		fi
	done
fi
